# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2019

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  Categories: /categories/
  # About: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

pjax: true

# LaTeX support (via MathJax)
latex: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /wechat.png
    alipay: /alipay.jpg

# ===========================================
# Social links Settings
# ===========================================
social:
  email: cycleke@gmail.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/cycleke
  weibo:
  zhihu: https://www.zhihu.com/people/cycleke-10/activities
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: RQJcuxPw8uLplWHjovTGN12P-gzGzoHsz
  app_key: lNYirj5D8lRylB6uB4cz4JTl

# Valine comment https://valine.js.org
valine:
  appid:  RQJcuxPw8uLplWHjovTGN12P-gzGzoHsz # your leancloud appid
  appkey: lNYirj5D8lRylB6uB4cz4JTl # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: Just go go # comment box placeholder

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# ===========================================
# Version
# ===========================================
version: 2.11.0
